### ISSUE TITLE
Shipping contract profit inconsistently uses tons or cubic meters to calculate

### ISSUE THREAD

**Issue by dhessels** [YarekTyshchenko/PMMGBeautifier#11]
I noticed this when viewing two very similar shipping ads. The larger of tons or cubic meters is not always used when calculating the profit per 400 tons / cubic meters. If I get a chance I'll look through the code to see if there is an intended reason for this.

![image](https://user-images.githubusercontent.com/2634908/87262896-749c4100-c470-11ea-83c6-1c08264ee9d5.png)

**Comment by YarekTyshchenko** [comment]
This has already been fixed by PR #9 
I'm having trouble pushing out the new version because of Chrome webstore suddenly requiring that icons and assets be present. I'm hoping to get it sorted in a few days
