### ISSUE TITLE
UserNames not displaying correctly after game update

### ISSUE THREAD

**Issue by solstone** [YarekTyshchenko/PMMGBeautifier#14]
Hello,  first off, awesome extension! Love it.

After the patch that occurred on 3/25/2021.  Names are not displaying correctly and are no longer clickable.

**Comment by YarekTyshchenko** [comment]
Thanks @solstone. Sounds like the devs have finally implemented name shortening, so we can probably take out the module entirely. Happy to accept a patch if you are willing to dip your toes in. Otherwise I'll have a look at it when I get some free time (tm)

**Comment by YarekTyshchenko** [comment]
Should be fixed by #a2b4b65 Removed the module
